### ISSUE TITLE
Planning to restart my bitcoin currency converter project,  your contributions are welcome. I plan to add other currencies 💱  and other coins,  aside a new user interface 

### ISSUE THREAD

**Issue by michaelNgiri** [michaelNgiri/bitcoin-currency-converter#1]

**Comment by simocosimo** [comment]
Do you have a starting project or it would be necessary to do it from scratch?

**Comment by michaelNgiri** [comment]
@simocosimo I have just a boilerplate code that I was supposed to build the project on. 

But you can make contributions any how you choose
